Notes order functionality
ievalu/notes-table pull request #1
Opened 2019-03-12 11:46 UTC by ievalu

2019-03-12 11:58 UTC, ptrdom approved these changes

2019-03-12 12:01 UTC, ptrdom requested changes

2019-03-12 12:01 UTC, ptrdom commented on app/controllers/Application.scala
> +          content = new java.io.File(s"C:/Users/ieva.lubyte/Desktop/uploaded-images/$noteId"),
Use path from configuration file instead of hardcoded one configuration.underlying.getString("pathForUploadedFiles").

2019-03-12 14:40 UTC, ptrdom approved these changes

2019-03-12 15:08 UTC, ptrdom requested changes

2019-03-12 15:08 UTC, ptrdom commented on app/controllers/Application.scala
> +          case _ => Ok(s"$nr notes deleted")
These should both redirect to notes table with either success or error message, instead of blank page with text.

2019-03-12 15:08 UTC, ptrdom commented on app/dao/NotesDAO.scala
> +      ))
Doesn't this throw errors if there is no file is uploaded?

2019-03-12 15:08 UTC, ptrdom commented on app/dao/NotesDAO.scala
> +      _ <- notes.insertOrUpdate(Note(noteId, note.text, "#f1d6c0", fileName))
Why is color hardcoded here, shouldn't it be taken from form?

2019-03-12 15:08 UTC, ptrdom commented on app/controllers/Application.scala
> +      )
Logic can be improved here, instead of:
```
someOption.map {
  case Some(value) =>
    someFunction(
      otherValue,
      Some(otherFunction(value))
    )
  case None =>
    someFunction(
      otherValue,
      None
    )
}
```
you can do:
```
someFunction(
  otherValue,
  someOption.map { value =>
    Some(otherFunction(value))
  }
)
```
Less code and clearer intended logic.

2019-03-12 15:08 UTC, ptrdom commented on app/controllers/Application.scala
> +          }
Logic can be improved here, instead of:
```
someOption.map {
  case Some(value) =>
    someFunction(
      otherValue,
      Some(otherFunction(value))
    )
  case None =>
    someFunction(
      otherValue,
      None
    )
}
```
you can do:
```
someFunction(
  otherValue,
  someOption.map { value =>
    Some(otherFunction(value))
  }
)
```
Less code and clearer intended logic.

2019-03-13 08:31 UTC, ievalu commented on app/dao/NotesDAO.scala
> +      ))
It doesn't

2019-03-29 10:27 UTC, merged